### ISSUE TITLE
Why passing connection pointer?

### ISSUE THREAD

**Issue by Raggaer** [rwxsu/goot#2]
So, multiple times, like: https://github.com/rwxsu/goot/blob/master/main.go#L70 you pass the connection as a pointer and then access the underlying value everywhere `(*c)`...

I was working on `main.go` to handle connections on a goroutine and just wanted to know.

Thanks

**Comment by wgrr** [comment]
@Raggaer I bet this is wrong, pointer to interfaces is pretty much never useful, that's why Go does not auto-defer an interface pointer.
Since net.TCPListerner uses pointers on method receivers, pointer to net.Conn is totally redundant, I'd recommend to change to just net.Conn
- wgr

**Comment by rwxsu** [comment]
@Raggaer Just my lack of skill in Go, I thought it _had_ to pass be passed by reference.

**Comment by rwxsu** [comment]
@wgrr Did you test login in? The pointer is necessary because you must be able to pass `(&c)` to the `net.Conn` interface argument in the IIFE in main. https://github.com/rwxsu/goot/blob/master/main.go#L105

To be able to do what you're saying `l.Accept()` needs to return an _actual_ connection, not an interface. https://github.com/rwxsu/goot/blob/master/main.go#L61

**Comment by wgrr** [comment]
@rwxsu interfaces are "references" types by default, such as maps and chans, you should not need a pointer there, but i didn't test, ill investigate that and open a new pr
